# <%= pkg %> <%= version %>
mutation update<%= name %>(
  $id: ID!
  $name: String
  #Boolean, Float, Int
) {
  update<%= name %>(
    id:$id
    input:{
      name:$name
    })
  {
    id
    updatedAt
  }
}



